export interface NicheTemplate {
  name: string;
  description: string;
  icpDescription: string;
  keywords: string[];
  targetJobTitles: string[];
  dailyConnectLimit: number;
  category: string;
}

export const NICHE_CATEGORIES = [
  'SaaS Founders',
  'MVP & Product Dev',
  'Web Dev Agencies',
  'Freelance Developers',
  'Digital & Marketing Agencies',
] as const;

export const NICHE_TEMPLATES: NicheTemplate[] = [

  // ─── SaaS Founders ───────────────────────────────────────────────────────────

  {
    category: 'SaaS Founders',
    name: 'Early-Stage SaaS Founders',
    description: 'Pre-seed to Series A founders building their first SaaS product',
    icpDescription: 'Early-stage SaaS founders struggling with team coordination, shipping fast, and managing tasks across a tiny team. They need lightweight project management that does not slow them down. Taskip directly solves their operational chaos without the enterprise bloat of Jira or Asana.',
    keywords: ['saas', 'founder', 'startup', 'mvp', 'product-market fit', 'early stage'],
    targetJobTitles: ['Founder', 'Co-Founder', 'CEO', 'CTO'],
    dailyConnectLimit: 5,
  },
  {
    category: 'SaaS Founders',
    name: 'Bootstrapped SaaS Builders',
    description: 'Self-funded founders running lean, profitable SaaS businesses',
    icpDescription: 'Bootstrapped SaaS founders who manage everything with a small team and no VC money. They are cost-conscious, tool-savvy, and hate paying for bloated software. Taskip appeals as a no-fluff task management tool built by a founder who understands their constraints.',
    keywords: ['bootstrapped', 'indie hacker', 'solopreneur', 'self-funded', 'mrr', 'ramen profitable', 'bootstrapping'],
    targetJobTitles: ['Founder', 'Indie Hacker', 'Solopreneur', 'CEO', 'Co-Founder'],
    dailyConnectLimit: 5,
  },
  {
    category: 'SaaS Founders',
    name: 'B2B SaaS Founders',
    description: 'Founders selling software to other businesses',
    icpDescription: 'B2B SaaS founders who sell to teams and businesses. They understand workflow pain points deeply and are always evaluating tools their own team uses. A conversation about Taskip is both a sales opportunity and a peer conversation about how they solve the same problems.',
    keywords: ['b2b saas', 'b2b software', 'saas startup', 'b2b founder', 'enterprise saas'],
    targetJobTitles: ['Founder', 'CEO', 'Co-Founder', 'CTO', 'Head of Product'],
    dailyConnectLimit: 5,
  },
  {
    category: 'SaaS Founders',
    name: 'No-Code SaaS Builders',
    description: 'Non-technical founders building SaaS with no-code tools',
    icpDescription: 'Non-technical founders building SaaS products using Bubble, Webflow, Make.com, and similar platforms. They move fast, value simplicity, and actively discuss building and growing their products on LinkedIn. They relate to a fellow founder who ships lean.',
    keywords: ['no-code', 'nocode', 'bubble', 'webflow', 'make.com', 'zapier', 'low-code', 'no code saas'],
    targetJobTitles: ['Founder', 'No-Code Developer', 'Product Builder', 'Entrepreneur', 'CEO'],
    dailyConnectLimit: 4,
  },
  {
    category: 'SaaS Founders',
    name: 'Micro-SaaS Operators',
    description: 'Founders running small, focused SaaS products solo or with 1-3 people',
    icpDescription: 'Micro-SaaS operators building niche software products that solve a specific problem. They run the whole operation — support, dev, marketing — with 1-3 people. They constantly share their journey on LinkedIn and are always looking for lightweight tools that save hours per week.',
    keywords: ['micro saas', 'microsaas', 'solo founder', 'one person startup', 'indie saas', 'side project'],
    targetJobTitles: ['Solo Founder', 'Founder', 'Indie Maker', 'Co-Founder', 'Developer'],
    dailyConnectLimit: 4,
  },
  {
    category: 'SaaS Founders',
    name: 'SaaS Founders Growing Past $10K MRR',
    description: 'Founders at the scaling inflection point needing better team tools',
    icpDescription: 'SaaS founders who have found product-market fit and are now scaling past $10K MRR. At this point they are hiring their first 3-10 employees and urgently need a structured way to manage tasks, sprint priorities, and cross-team visibility. Taskip is the natural upgrade from sticky notes and Slack threads.',
    keywords: ['mrr', 'arr', 'saas growth', 'scaling startup', 'saas metrics', 'product-market fit'],
    targetJobTitles: ['Founder', 'CEO', 'Co-Founder', 'Head of Operations'],
    dailyConnectLimit: 5,
  },
  {
    category: 'SaaS Founders',
    name: 'Remote-First SaaS Teams',
    description: 'Distributed SaaS teams needing async task management',
    icpDescription: 'SaaS founders managing fully remote or hybrid teams across time zones. They struggle with async visibility into who is working on what, missed deadlines, and status updates that fall through Slack gaps. Taskip gives them a real-time task board their team actually updates.',
    keywords: ['remote team', 'remote first', 'async', 'distributed team', 'remote work', 'work from anywhere'],
    targetJobTitles: ['Founder', 'CEO', 'Operations Lead', 'Chief of Staff', 'Head of Remote'],
    dailyConnectLimit: 5,
  },
  {
    category: 'SaaS Founders',
    name: 'SaaS Co-Founders (Technical + Business Split)',
    description: 'Technical and business co-founder pairs building together',
    icpDescription: 'Two-person co-founder teams where one builds and one sells. They need a shared task system that keeps both sides aligned without daily check-ins — something that bridges the dev sprint board and the business side to-do list in one place.',
    keywords: ['co-founder', 'technical co-founder', 'founding team', 'startup cofounder', 'co founder'],
    targetJobTitles: ['Co-Founder', 'CTO', 'Founder', 'Technical Founder', 'CEO'],
    dailyConnectLimit: 4,
  },

  // ─── MVP & Product Dev ────────────────────────────────────────────────────────

  {
    category: 'MVP & Product Dev',
    name: 'First-Time Founders Building MVP',
    description: 'Entrepreneurs building their first product from scratch',
    icpDescription: 'First-time entrepreneurs who have a validated idea and are building their MVP. They are figuring out everything at once — product, tech, customers — and need a dead-simple task system to stay focused on what matters this sprint without drowning in complexity.',
    keywords: ['mvp', 'minimum viable product', 'first startup', 'idea validation', 'building in public', 'build in public'],
    targetJobTitles: ['Founder', 'Entrepreneur', 'CEO', 'Co-Founder', 'Product Builder'],
    dailyConnectLimit: 5,
  },
  {
    category: 'MVP & Product Dev',
    name: 'Entrepreneurs Hiring Dev Agencies for MVP',
    description: 'Non-technical founders outsourcing their product development',
    icpDescription: 'Non-technical founders who are paying a web or dev agency to build their MVP. They need to manage requirements, review deliverables, and track progress without being technical. Taskip gives them a shared workspace to communicate tasks clearly with their development partner.',
    keywords: ['mvp development', 'outsource development', 'hire developers', 'product development', 'app development'],
    targetJobTitles: ['Founder', 'CEO', 'Entrepreneur', 'Product Owner', 'Startup Founder'],
    dailyConnectLimit: 5,
  },
  {
    category: 'MVP & Product Dev',
    name: 'Product Managers at Startups',
    description: 'PMs who own roadmap and sprint delivery at early-stage companies',
    icpDescription: 'Product managers at startups who manage backlogs, run sprints, and coordinate between engineering, design, and leadership. They are the power users of PM tools and drive tool adoption decisions within their organizations. Taskip competes directly with their current setup.',
    keywords: ['product manager', 'product management', 'roadmap', 'sprint planning', 'agile', 'scrum'],
    targetJobTitles: ['Product Manager', 'Senior PM', 'Head of Product', 'Director of Product', 'VP Product'],
    dailyConnectLimit: 4,
  },
  {
    category: 'MVP & Product Dev',
    name: 'Web App & Mobile App Builders',
    description: 'Technical founders shipping web and mobile applications',
    icpDescription: 'Technical founders and small engineering teams building web or mobile applications for their startup. They juggle feature development, bug fixes, and customer requests in parallel and need a task board that fits their fast-moving workflow without project management ceremony.',
    keywords: ['web app', 'mobile app', 'app development', 'react', 'nextjs', 'flutter', 'react native', 'saas app'],
    targetJobTitles: ['Technical Founder', 'CTO', 'Full Stack Developer', 'Co-Founder', 'Lead Developer'],
    dailyConnectLimit: 4,
  },
  {
    category: 'MVP & Product Dev',
    name: 'Startup Operators & Chief of Staff',
    description: 'Ops leaders managing execution across a startup',
    icpDescription: 'Startup operators, chiefs of staff, and heads of operations who keep the company running — coordinating between teams, tracking priorities, and making sure nothing falls through the cracks. They are primary buyers and daily power users of project management tools.',
    keywords: ['operations', 'chief of staff', 'startup ops', 'internal ops', 'process', 'execution'],
    targetJobTitles: ['Chief of Staff', 'Head of Operations', 'VP Operations', 'Operations Manager', 'COO'],
    dailyConnectLimit: 4,
  },
  {
    category: 'MVP & Product Dev',
    name: 'Consultants Who Build Products for Clients',
    description: 'Independent consultants scoping and delivering product builds',
    icpDescription: 'Independent tech or product consultants who scope, design, and oversee delivery of digital products for client businesses. They manage client expectations and developer teams simultaneously and need a clear task and milestone tracker to maintain professional delivery standards.',
    keywords: ['product consultant', 'tech consultant', 'fractional cto', 'fractional cpo', 'product strategy'],
    targetJobTitles: ['Fractional CTO', 'Fractional CPO', 'Product Consultant', 'Independent Consultant', 'Tech Advisor'],
    dailyConnectLimit: 4,
  },

  // ─── Web Dev Agencies ─────────────────────────────────────────────────────────

  {
    category: 'Web Dev Agencies',
    name: 'Full-Service Web Development Agencies',
    description: 'Agencies handling design, development, and launch end-to-end',
    icpDescription: 'Web development agency owners managing 5-30 active client projects simultaneously. They coordinate designers, developers, and project managers and need a central task hub to track milestones, client revisions, and sprint deliverables across every project without losing visibility.',
    keywords: ['web development agency', 'web agency', 'full service agency', 'custom website', 'web development'],
    targetJobTitles: ['Agency Owner', 'Managing Director', 'CEO', 'Technical Director', 'Founder'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Web Dev Agencies',
    name: 'WordPress Development Agencies',
    description: 'Agencies that specialize in WordPress websites for clients',
    icpDescription: 'WordPress-focused agency owners building and maintaining client websites using themes, page builders, and plugins. They purchase premium plugins at scale, need reliable vendors, and struggle to manage client scope creep and revision cycles. Both a Taskip and Xgenious audience.',
    keywords: ['wordpress agency', 'wordpress development', 'wordpress website', 'wp agency', 'wordpress consultant'],
    targetJobTitles: ['WordPress Agency Owner', 'Agency Owner', 'Technical Director', 'Managing Director'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Web Dev Agencies',
    name: 'App Development Agencies',
    description: 'Agencies building mobile and web applications for clients',
    icpDescription: 'App development agencies building custom web and mobile applications for SMBs and startups. They manage complex multi-month delivery cycles across product, design, and engineering teams and need project management that gives clients visibility without exposing internal chaos.',
    keywords: ['app development agency', 'mobile app agency', 'software development agency', 'custom software', 'app agency'],
    targetJobTitles: ['Agency Owner', 'CEO', 'Director of Engineering', 'Technical Lead', 'Delivery Manager'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Web Dev Agencies',
    name: 'E-commerce Development Agencies',
    description: 'Agencies building Shopify and WooCommerce stores',
    icpDescription: 'E-commerce development agencies specializing in Shopify, WooCommerce, and custom store builds. They manage product catalog setup, payment integration, and ongoing retainers for multiple clients. They need task management that tracks both new builds and ongoing client maintenance.',
    keywords: ['ecommerce agency', 'shopify agency', 'woocommerce agency', 'ecommerce development', 'shopify partner'],
    targetJobTitles: ['Agency Owner', 'E-commerce Lead', 'Technical Director', 'Founder', 'CEO'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Web Dev Agencies',
    name: 'SaaS Development Agencies',
    description: 'Agencies that build SaaS products for startup clients',
    icpDescription: 'Development agencies that specialize in building SaaS MVPs and products for startup clients. They handle everything from architecture to launch and need sprint-based task management to deliver on time. They are also potential referrers of Taskip to the startups they serve.',
    keywords: ['saas development', 'saas agency', 'mvp agency', 'product development agency', 'startup development'],
    targetJobTitles: ['Agency Owner', 'CEO', 'CTO', 'Founder', 'Lead Developer'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Web Dev Agencies',
    name: 'UI/UX Design Agencies',
    description: 'Design agencies delivering product and brand design to clients',
    icpDescription: 'UI/UX design agencies that handle product design, brand identity, and user experience for startups and SMBs. They manage feedback rounds, design iterations, and handoff to client dev teams. They need task management that handles creative workflows, not just software sprints.',
    keywords: ['ui ux agency', 'design agency', 'product design', 'ux agency', 'creative agency design'],
    targetJobTitles: ['Design Agency Owner', 'Creative Director', 'Design Lead', 'Founder', 'UX Lead'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Web Dev Agencies',
    name: 'Outsourcing & Offshore Dev Shops',
    description: 'Teams offering dedicated development to international clients',
    icpDescription: 'Offshore and outsourcing development agencies in South Asia providing dedicated developer teams to international clients. They win clients on price but retain them on quality and communication. They need robust task and milestone tracking to maintain transparency with overseas clients.',
    keywords: ['outsourcing', 'offshore development', 'dedicated team', 'offshore agency', 'nearshore', 'software outsourcing'],
    targetJobTitles: ['CEO', 'Director of Operations', 'Delivery Manager', 'Account Manager', 'Founder'],
    dailyConnectLimit: 5,
  },

  // ─── Freelance Developers ─────────────────────────────────────────────────────

  {
    category: 'Freelance Developers',
    name: 'Full-Stack Freelance Developers',
    description: 'Independent developers handling both frontend and backend for clients',
    icpDescription: 'Full-stack freelance developers managing 2-5 client projects at a time. They handle requirements, design feedback, and deployments solo. They need a lightweight task system to stay on top of everything without the overhead of tools designed for enterprise teams.',
    keywords: ['full stack developer', 'freelance developer', 'fullstack', 'web developer', 'freelance web dev'],
    targetJobTitles: ['Freelance Developer', 'Full Stack Developer', 'Software Developer', 'Independent Developer'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Freelance Developers',
    name: 'WordPress Freelancers',
    description: 'Independent WordPress developers working with multiple clients',
    icpDescription: 'Freelance WordPress developers building and maintaining client sites. They regularly purchase premium plugins and themes to speed up client delivery. Direct audience for both Xgenious products (as plugin buyers) and Taskip (as multi-client task managers).',
    keywords: ['wordpress freelancer', 'wordpress developer', 'wp freelancer', 'wordpress', 'elementor developer'],
    targetJobTitles: ['WordPress Developer', 'Freelance Developer', 'Web Developer', 'WordPress Consultant'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Freelance Developers',
    name: 'Freelance Mobile App Developers',
    description: 'Independent developers building iOS and Android apps for clients',
    icpDescription: 'Freelance mobile app developers building iOS and Android apps for startup and SMB clients. They often manage multiple client builds in parallel and struggle to communicate project status, manage feedback, and track tasks across different clients without a proper system.',
    keywords: ['mobile developer', 'ios developer', 'android developer', 'flutter developer', 'react native developer', 'freelance mobile'],
    targetJobTitles: ['Mobile Developer', 'iOS Developer', 'Android Developer', 'Flutter Developer', 'Freelancer'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Freelance Developers',
    name: 'Freelance UI/UX Designers',
    description: 'Independent designers delivering product and brand design',
    icpDescription: 'Freelance UI/UX designers managing client design projects from wireframe to handoff. They handle multiple feedback rounds, present to non-technical stakeholders, and hand off to developers — all without a team. They need a simple task tracker that keeps client work organized.',
    keywords: ['freelance designer', 'ui ux designer', 'freelance ux', 'product designer', 'figma designer', 'ui designer'],
    targetJobTitles: ['Freelance Designer', 'UI UX Designer', 'Product Designer', 'Graphic Designer', 'Independent Designer'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Freelance Developers',
    name: 'Upwork & Fiverr Top Sellers',
    description: 'High-earning freelancers on major freelance marketplaces',
    icpDescription: 'Top-rated freelancers on Upwork, Fiverr, and Toptal who manage multiple concurrent contracts. They are serious about their reputation, always deliver on time, and need tools that help them stay organized when juggling 3-8 clients without anything falling through the cracks.',
    keywords: ['upwork', 'fiverr', 'toptal', 'freelance marketplace', 'upwork freelancer', 'fiverr seller'],
    targetJobTitles: ['Freelancer', 'Top Rated Freelancer', 'Independent Contractor', 'Consultant'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Freelance Developers',
    name: 'Freelance No-Code Developers',
    description: 'Freelancers building client projects with Bubble, Webflow, Glide, and similar',
    icpDescription: 'No-code freelancers who build client websites, apps, and automations using tools like Webflow, Bubble, Glide, and Make.com. They are fast builders who value simple tooling and are active LinkedIn content creators sharing their builds and client wins.',
    keywords: ['no-code freelancer', 'webflow developer', 'bubble developer', 'no code developer', 'webflow freelancer'],
    targetJobTitles: ['No-Code Developer', 'Webflow Developer', 'Bubble Developer', 'Freelancer', 'Automation Specialist'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Freelance Developers',
    name: 'Freelance Backend & API Developers',
    description: 'Backend specialists building APIs, databases, and integrations',
    icpDescription: 'Freelance backend developers specializing in APIs, databases, and third-party integrations. They are often brought in mid-project by agencies or non-technical founders and need to quickly understand task scope and communicate progress without long meetings.',
    keywords: ['backend developer', 'api developer', 'node.js', 'python developer', 'backend freelance', 'rest api'],
    targetJobTitles: ['Backend Developer', 'API Developer', 'Software Engineer', 'Freelance Developer', 'Node.js Developer'],
    dailyConnectLimit: 4,
  },

  // ─── Digital & Marketing Agencies ────────────────────────────────────────────

  {
    category: 'Digital & Marketing Agencies',
    name: 'Full-Service Digital Agencies',
    description: 'Agencies offering web, design, SEO, and marketing under one roof',
    icpDescription: 'Full-service digital agency owners juggling web design, SEO, paid ads, and social for dozens of clients simultaneously. They have account managers, designers, developers, and content writers all needing to see their tasks in one place. Taskip is the operational backbone they need.',
    keywords: ['digital agency', 'full service agency', 'agency owner', 'agency growth', 'digital marketing agency'],
    targetJobTitles: ['Agency Owner', 'Managing Director', 'CEO', 'Founder', 'Operations Director'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'SEO & Content Marketing Agencies',
    description: 'Agencies delivering organic growth through SEO and content',
    icpDescription: 'SEO and content agency owners managing writers, link builders, and client deliverables at scale. They produce dozens of articles, audits, and reports per month and need a task system that tracks the full content pipeline from keyword research to published post.',
    keywords: ['seo agency', 'content agency', 'content marketing', 'seo', 'link building', 'organic growth'],
    targetJobTitles: ['SEO Agency Owner', 'Content Marketing Director', 'Head of SEO', 'Founder', 'CEO'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'Performance & Paid Ads Agencies',
    description: 'Agencies running Google, Meta, and paid campaigns for clients',
    icpDescription: 'Paid advertising agency owners managing Google Ads, Meta Ads, and performance campaigns for multiple clients. They track budgets, creative iterations, and A/B tests across accounts and need a task manager that keeps campaigns on track and nothing slipping through.',
    keywords: ['paid ads', 'performance marketing', 'google ads', 'facebook ads', 'meta ads', 'ppc agency'],
    targetJobTitles: ['Agency Owner', 'Head of Performance', 'Paid Media Director', 'Founder', 'Media Buyer'],
    dailyConnectLimit: 5,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'Social Media Marketing Agencies',
    description: 'Agencies managing brand social media presence for clients',
    icpDescription: 'Social media agency owners managing content calendars, community engagement, and platform growth for multiple client brands. They coordinate content creators, designers, and copywriters against tight publishing schedules and need visibility into every task without daily standups.',
    keywords: ['social media agency', 'smm agency', 'social media management', 'content creation agency', 'social media marketing'],
    targetJobTitles: ['Social Media Agency Owner', 'Head of Social', 'Content Manager', 'Founder', 'CEO'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'Branding & Creative Studios',
    description: 'Studios delivering brand identity and creative direction',
    icpDescription: 'Creative studio and branding agency owners who deliver logo systems, brand guidelines, and creative campaigns. They work in iterative creative rounds with clients and need a task tracker that handles feedback-heavy, revision-rich workflows rather than code sprints.',
    keywords: ['branding agency', 'creative studio', 'brand identity', 'graphic design agency', 'creative agency'],
    targetJobTitles: ['Studio Owner', 'Creative Director', 'Brand Designer', 'Art Director', 'Founder'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'Email & Automation Marketing Agencies',
    description: 'Agencies delivering email sequences, CRM flows, and marketing automation',
    icpDescription: 'Email marketing and automation agencies building campaign sequences, CRM workflows, and lifecycle journeys for clients. They manage complex multi-step projects with tight deadlines and need a system that tracks every deliverable from strategy to final approval.',
    keywords: ['email marketing agency', 'marketing automation', 'klaviyo agency', 'crm agency', 'hubspot agency'],
    targetJobTitles: ['Agency Owner', 'Email Marketing Director', 'Head of Automation', 'Founder', 'CRM Strategist'],
    dailyConnectLimit: 4,
  },
  {
    category: 'Digital & Marketing Agencies',
    name: 'Growth & Lead Generation Agencies',
    description: 'Agencies focused on outbound, lead gen, and pipeline growth for clients',
    icpDescription: 'Lead generation and growth agency owners running outbound campaigns, cold email sequences, and LinkedIn outreach for B2B clients. They are power users of outreach tools and are themselves the target audience for demonstrating how Taskip keeps their own operations tight.',
    keywords: ['lead generation', 'growth agency', 'outbound agency', 'b2b lead gen', 'cold outreach', 'sales agency'],
    targetJobTitles: ['Agency Owner', 'Head of Growth', 'Lead Gen Specialist', 'Founder', 'CEO'],
    dailyConnectLimit: 5,
  },
];
